# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["tim@1stdibs.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript-default"
description = "Testing streaming options"
language = "javascript"
manifest_version = 3
name = "fastly-streaming-poc"
service_id = ""

[scripts]
    build = "npm run build"
    post_init = "npm install"

[local_server]

    [local_server.backends]

        [local_server.backends.origin_0]
            url = "http://localhost:3000"
